#!/usr/bin/env bash

# ls aliases
alias ls="ls --group-directories-first --color=auto"
alias lss="ls++ --potsf -A --group-directories-first --sort=extension"
alias lsa="exa -lhagm --color-scale --group-directories-first --sort=type --git"

# Quick navigation
alias dow='cd ~/Downloads'
alias down='dow'
alias doc='cd ~/Documents'
alias pic='cd ~/Documents/Pictures'
alias mov='cd ~/Documents/Videos'
alias dot="cd ~/.dotfiles"
alias drop='cd ~/Dropbox'
alias bin="cd ~/.dotfiles/bin/"
alias blocks="cd ~/.config/i3/blocks"

# Dotfiles configs
alias bashrc='vim ~/.bashrc'
alias zshrc='vim ~/.zshrc'
alias profile='vim ~/.profile'
alias gitconf='vim ~/.gitconfig'
alias xinitrc='vim ~/.xinitrc'
alias xresources='vim ~/.dotfiles/.Xresources'
alias aliases='vim ~/.dotfiles/aliases'
alias shellrc='vim ~/.dotfiles/shellrc'
alias mimeapps='vim ~/.config/mimeapps.list'
alias userdirs='vim ~/.config/user-dirs.dirs'
alias i3conf='vim ~/.config/i3/config'
alias i3bconf='vim ~/.config/i3/i3blocks'
alias i3confn='vim ~/.config/i3/config.notebook'
alias i3bconfn='vim ~/.config/i3/i3blocks.notebook'
alias vimrc='vim ~/.vimrc'
alias nvimupdate='nvim +PluginInstall +qall'
alias xresources='vim ~/.dotfiles/.Xresources'
alias chfeedlykey="vim ~/.dotfiles/secret -c '5:normal ci\"' -c ':normal \"*p' -c ':wq'; i3-msg restart"

# System aliases
alias sudo='sudo '
alias vim='nvim'
alias py='python3'
alias ipy='ipython3'
alias sx='startx'
alias src='source ~/.dotfiles/shellrc'
alias ztail="zless"
alias neo="neofetch"
alias sys="systemctl"
alias xru="xrdb ~/.dotfiles/.Xresources"
alias up="yay --batchinstall --combinedupgrade --noeditmenu --noconfirm -Syyu"
alias duh="du -sch * | sort -h"
alias shells="sed 's/.*\///g; s/^[#].*//g' /etc/shells | sort | uniq | nl | column -t"
alias scrotscr='scrot ${SCREENSHOTS_DIR}/$(date %Y-%m-%d-%T).png || mkdir -p ${SCREENSHOTS_DIR}'
alias plexon="sudo systemctl start plexmediaserver.service"
alias plexoff="sudo systemctl stop plexmediaserver.service"
alias stremioff="ps aux | grep -i stremio | grep -v grep | cut -d' ' -f2 | xargs kill"
alias pmgrep="pacman -Q | grep -i "
alias hgrep="history | egrep -i --color "
alias psgrep="ps -NC grep | grep -i "
alias garb="garbarage"
alias binfo="bootinfo"
alias sysup="systemupgrade"
alias esa="exa -Flamg -s type --git"

