#!/usr/bin/env bash

export PATH="$PATH:$HOME/.dotfiles/bin:/snap/bin/"
export LANG="pt_BR.UTF-8"
export LANGUAGE="pt_BR.UTF-8"
export LC_ALL="pt_BR.UTF-8"
export ARCHFLAGS="-arch x86_64"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"
export EDITOR="vim"
export HISTTIMEFORMAT="%d/%m/%Y %T   "
export QT_QPA_PLATFORMTHEME="qt5ct"
#export QT_QPA_PLATFORMTHEME="kde"
export TERM="xterm-256color"
export PYTHONDONTWRITEBYTECODE=true
export SCREENSHOTS_DIR="$HOME/Documents/Pictures/screenshots"
export WALLPAPERS_PATH="$HOME/Dropbox/pictures/wallpapers"
export XDG_CURRENT_DESKTOP=i3
export XDG_SESSION_DESKTOP=i3
export DESKTOP_SESSION=i3
export GOPATH=$HOME/.go

[[ -f ~/.dotfiles/insulter ]] && . ~/.dotfiles/insulter
[[ -f ~/.dotfiles/aliases ]] && . ~/.dotfiles/aliases
[[ -f ~/.dotfiles/secret ]] && . ~/.dotfiles/secret

#eval "$(thefuck --alias)" && alias fuck="fuck -y"
psgrep $$ | grep zsh > /dev/null && alias history="fc -li 1000"



if [[ $(sudo fgconsole 2>/dev/null) == 1 ]]; then
    if ! pgrep xinit > /dev/null; then
        startx -- vt1
    fi
fi


kubectl () {
    command kubectl $*
    if [[ -z $KUBECTL_COMPLETE ]]
    then
        source <(command kubectl completion zsh)
        KUBECTL_COMPLETE=1 
    fi
}
