#!/usr/bin/env bash


which ufw >/dev/null || { echo "ufw não instalado"; exit 1 ;} 

status=$(sudo ufw status 2> /dev/null)
[[ "${status}" != *inactive* ]] && echo "<span background='red' foreground='white'>ON</span>" || echo "OFF"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  sudo ufw enable
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  sudo ufw reload
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  sudo ufw disable
fi

