#!/usr/bin/env bash

brightnessctl() {
    case ${BLOCK_BUTTON} in
        4) light -A 5 ; echo "$(light | sed 's/\...//g')%" ;;
        5) light -U 5 ; echo "$(light | sed 's/\...//g')%" ;;
        *) echo "$(light | sed 's/\...//g')%"
    esac
}

getKeystatp() {
    TYPE="${BLOCK_INSTANCE:-caps}"

    lockLine=$(xset -q | grep "Num Lock")

    capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
    numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
    scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

    if [[ "${TYPE}" == "caps" ]]; then
        checkLock="${capsLock}"
    elif [[ "${TYPE}" == "num" ]]; then
        checkLock="${numLock}"
    elif [[ "${TYPE}" == "scroll" ]]; then
        checkLock="${scrollLock}"
    else
        exit
    fi

    if [[ "${checkLock}" == "on" ]]; then
        echo "on"
    fi
}

getWebcamStatus() {
    if [[ -c /dev/video0 ]]; then
        if [[ "$(fuser /dev/video0)" != "" ]]; then
            echo "rec"
        fi
    else
        exit 1
    fi
}

microphonectl() {
    statusLine=$(amixer get Capture | tail -n 1)
    status=$(echo "${statusLine}" | grep -wo "on")
    volume=$(echo "${statusLine}" | awk '{print $4}' | tr -d '[]')

    #[[ "${status}" == "on" ]] && echo "${volume}%" || echo "off"

    case ${BLOCK_BUTTON} in
        1) amixer -q sset Capture 80%; echo "${volume}" ;;
        2) amixer -q sset Capture 0%; echo "${volume}" ;;
        3) amixer -q sset Capture toggle; echo "${volume}" ;;
        4) echo "${volume}" ; amixer -q sset Capture 5%+ ;;
        5) echo "${volume}" ; amixer -q sset Capture 5%- ;;
        *) echo "${volume}" ;;
    esac
}

batteryctl() {
    BATTERY=0
    BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
    BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
    BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

    URGENT_VALUE=10

    if [[ "${BATTERY_STATE}" = "Charging" ]]; then
        echo "${BATTERY_POWER}%+"
    elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
        echo "${BATTERY_POWER}%-"
    else
        echo "${BATTERY_POWER}%"
    fi

    if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
        exit 33
    fi
}


instance="${BLOCK_INSTANCE:-brightness}"
case "${instance}" in
    'brightness') brightnessctl                                     ;;
    'bluetooth')  [ pgrep bluetooth ] && echo 'on' || echo 'off' ;;
    'keystat')    getKeystatp                                       ;;
    'webcam')     getWebcamStatus                                   ;;
    'microphone') microphonectl                                     ;;
    'battery')   batteryctl                                         ;;
esac
