#!/usr/bin/env bash

ACTIVE_MONITORS=$(xrandr --listactivemonitors | grep -v Monitors | wc -l)
case "${BLOCK_BUTTON}" in
    3)
        if [[ "${ACTIVE_MONITORS}" -eq 2 ]]; then
            # from dual to single
            MODE=single
            xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-3 --off --output HDMI-0 --off --output DP-4 --off --output DP-5 --off
            notify-send "Screen" "Change to [${MODE}] screen" -t 5000
            i3-msg restart
        elif [[ "${ACTIVE_MONITORS}" -eq 1 ]]; then
            # from single to dual
            MODE=dual
            xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-3 --off --output HDMI-0 --mode 1920x1080 --pos 0x180 --rotate normal --output DP-4 --off --output DP-5 --off
            notify-send "Screen" "Change to [${MODE}] screen" -t 5000
            i3-msg restart
        fi

        nitrogen --restore
    ;;
    *)
        echo "${ACTIVE_MONITORS}"
    ;;
esac
